"""Deterministically rasterize Glimmerville's original SVG pixel icon."""

from __future__ import annotations

import argparse
from fractions import Fraction
from hashlib import sha256
from io import BytesIO
from pathlib import Path
from xml.etree import ElementTree

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parent
SVG_PATH = ROOT / "icon.svg"
BACKGROUND = "#0d1226"
OUTPUTS = (
    ("icon-v1-192.png", 192, False),
    ("icon-v1-512.png", 512, False),
    ("icon-v1-maskable-512.png", 512, True),
)


def parse_hex(color: str) -> tuple[int, int, int]:
    if len(color) != 7 or not color.startswith("#"):
        raise ValueError(f"Only #RRGGBB fills are supported: {color!r}")
    return tuple(int(color[index : index + 2], 16) for index in (1, 3, 5))


def exact_int(value: Fraction, label: str) -> int:
    if value.denominator != 1:
        raise ValueError(f"{label} is not pixel-aligned: {value}")
    return value.numerator


def load_rects() -> tuple[tuple[int, int, int], list[tuple[Fraction, Fraction, Fraction, Fraction, tuple[int, int, int]]]]:
    root = ElementTree.parse(SVG_PATH).getroot()
    view_box = tuple(Fraction(part) for part in root.attrib.get("viewBox", "").split())
    if view_box != (0, 0, 16, 16):
        raise ValueError(f"Expected viewBox 0 0 16 16, got {view_box!r}")

    rects = []
    for element in root.iter():
        if element.tag.rsplit("}", 1)[-1] != "rect":
            continue
        rects.append(
            (
                Fraction(element.attrib["x"]),
                Fraction(element.attrib["y"]),
                Fraction(element.attrib["width"]),
                Fraction(element.attrib["height"]),
                parse_hex(element.attrib["fill"].lower()),
            )
        )
    if not rects:
        raise ValueError("icon.svg has no rect geometry")

    background = parse_hex(BACKGROUND)
    full_background = (Fraction(0), Fraction(0), Fraction(16), Fraction(16), background)
    if rects[0] != full_background:
        raise ValueError("icon.svg first rect must remain the documented #0d1226 full background")
    return background, rects[1:]


def draw_rects(
    image: Image.Image,
    rects: list[tuple[Fraction, Fraction, Fraction, Fraction, tuple[int, int, int]]],
    *,
    logical_size: int,
    foreground_scale: Fraction,
    offset: Fraction,
) -> None:
    unit = Fraction(image.width, logical_size)
    draw = ImageDraw.Draw(image)
    for x, y, width, height, fill in rects:
        left = exact_int((offset + x * foreground_scale) * unit, "left")
        top = exact_int((offset + y * foreground_scale) * unit, "top")
        right = exact_int((offset + (x + width) * foreground_scale) * unit, "right")
        bottom = exact_int((offset + (y + height) * foreground_scale) * unit, "bottom")
        draw.rectangle((left, top, right - 1, bottom - 1), fill=fill)


def encode_icon(size: int, maskable: bool, background: tuple[int, int, int], rects: list) -> bytes:
    image = Image.new("RGB", (size, size), background)
    if maskable:
        draw_rects(
            image,
            rects,
            logical_size=32,
            foreground_scale=Fraction(3, 2),
            offset=Fraction(4),
        )
        radius = size * 0.4
        center = size / 2
        foreground = 0
        for y in range(size):
            for x in range(size):
                if image.getpixel((x, y)) == background:
                    continue
                foreground += 1
                distance_sq = (x + 0.5 - center) ** 2 + (y + 0.5 - center) ** 2
                if distance_sq > radius**2:
                    raise ValueError(f"Maskable foreground escapes safe zone at ({x},{y})")
        if foreground == 0:
            raise ValueError("Maskable icon has no foreground pixels")
    else:
        if size % 16:
            raise ValueError(f"Any icon size must be an integer multiple of 16: {size}")
        draw_rects(
            image,
            rects,
            logical_size=16,
            foreground_scale=Fraction(1),
            offset=Fraction(0),
        )

    output = BytesIO()
    image.save(output, format="PNG", optimize=False, compress_level=9)
    return output.getvalue()


def main(*, check: bool = False) -> None:
    background, rects = load_rects()
    mismatches = []
    for filename, size, maskable in OUTPUTS:
        data = encode_icon(size, maskable, background, rects)
        target = ROOT / filename
        matches = target.exists() and target.read_bytes() == data
        if check and not matches:
            mismatches.append(filename)
        elif not check and not matches:
            target.write_bytes(data)
        print(f"{filename} {len(data)} bytes sha256={sha256(data).hexdigest().upper()}")
    if mismatches:
        raise SystemExit("generated bytes differ: " + ", ".join(mismatches))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail on drift without writing files",
    )
    main(check=parser.parse_args().check)
